### ISSUE TITLE
[help wanted] 有些界面xml信息不准确

### ISSUE THREAD

**Issue by lln556** [TSKGHS17/UIAnalyzer#2]
如图所示，在有些界面，例如出现弹窗或下拉框的界面里，xml提供的信息还停留在主页面里。这个有办法解决吗？
![screenshot_SoM](https://github.com/user-attachments/assets/170c2e0d-cd22-4d73-8906-eee78f21c3b2)

**Comment by TSKGHS17** [comment]
用XML解析页面元素难以避免这个问题，你可以考虑写一些rule清洗不准确的数据

**Comment by TSKGHS17** [comment]
更新了使用OCR清洗XML元素的功能，部分解决了这个问题~
